### ISSUE TITLE
Autosaves and scripts

### ISSUE THREAD

**Issue by sheson** [sri-arjuna/SSE-CLA#4]
Where are the crash logs that that are the base for the conclusion that scripts being active while saving is a problem?

Such issues should be reported to the official DynDOLOD support forum, so it can be dealt with properly for the hundreds of thousands of users.

Messages in the analyzer should direct people to the official DynDOLOD support for qualified help and advice or to properly report problems in order to have them addressed properly.

**Comment by sri-arjuna** [comment]
I've had a talk with someone who had reported another issue, seening DynDOLOD in his loadorder.
Had asked him for any advice - as I've seen it listed a few times (really, just 2-3 times, not many).

He replied that disabling autosave - a vanilla game option - had solved/removed crashes on location changes for him.
He argued that while 'exiting' (a door for example), the game would start to render the enviornment, thus 'involving' DynDOLOD - mainwhile trying to save the game, which can cause freezes.

This is not really a DynDOLOD issue, but how Skyrim does auto saves.
Unless you're saying that DynDOLOD could "fix" this, then I'll happily add their URL to the "report" for any future / further issues.

And to answer your question, we dont see any active scripts in crashlogs.
Thus, there are no such crashlogs to "prove" that.

But what he said, sounded valid in my ears, as it made the most sense to those few crashlogs that were constantly crashing when exiting doors - because (all of) those users had DynDOLOD in their list.

Meanwhile, autosave is enabled  by default - which most users do not change at all.
Thus, for a "user error", I did not want to send people over there.

But yes, for next update, I can add the URL anyway, "just in case" and say something like:
> If this does not solve your issue, please contact the DynDOLOD team..

**Comment by sri-arjuna** [comment]
And to answer your question, we dont see any active scripts in crashlogs.
Thus, there are no such crashlogs to prove that.

But what he said, sounded valid in my ears, as it made the most sense to those few crashlogs that were constantly crashing when exiting doors - because (all of) those users had DynDOLOD in their list.

Meanwhile, autosave is enabled  by default - which most users do not change at all.
Thus, for a "user error", I did not want to send people over there.

But yes, for next update, I can add the URL anyway, "just in case" and say something like:
> If this does not solve your issue, please contact the DynDOLOD team..

**Comment by sheson** [comment]
If disabling autosaves addresses an issue with the DynDOLOD plugins/scripts, then there should be no problem to provide evidence like crash logs etc. so that the issue can be looked at, troubelshooted and fixed.

It sounds like instructions to disable autosaves and the reason are based on comments of a user making random assumptions without checking the crash log and having some actual understanding how the engine and DynDOLOD works. A crash log should point to the VM and/or saving/loading game data or to records in the DynDOLOD plugins or assets being used. Users having mods in the load order when a problem happens does not mean the mods are involved. Rudimentary troubleshooting would be to test without the suspected mods.

The DynDOLOD scripts work the same way since 2014. The engine freezes the state of scripts when saving and usually continues them without issue after loading them. There are related messages in the papyrus log. If saving would cause scripts to not finish, it would be a well known problem. The explanations and solution does not make sense right now and as such does not actually help to fix or understand the real cause of whatever the issue.

Typically the worse that can happen if a DynDOLOD scripts does not finish (because of stack dumping for example) is wrong enable/disable states for references. But only if the papyrus scripted dynamic LOD is actually used.

The way DynDOLOD works and is developed is that every issue is looked at and gets a qualified response or troubleshooting in order to fix the actual cause of the issue. Users are asked/required to report all issues to the official DynDOLOD support forum, especially if the believed reason involves DynDOLOD or believing having to do workarounds that are not part of its official documentation.

**Comment by sri-arjuna** [comment]
There is no point anywhere i said that DynDOLOD was "faulty" or buggy or anything.

Only that your very own suggestion / recomendation would help to avoid possible freezes or CTDs.
--> https://stepmodifications.org/forum/topic/13451-xlodgen-terrain-lod-beta-99-for-fnv-fo3-fo4-fo4vr-tes5-sse-tes5vr-enderal-enderalse/?do=findComment&comment=272457

These are 2 of the "landscape" related crashlogs that I had recieved.
By "landscape" i mean the users reported something along the line: "I exit location X and enter world at Y"
https://pastebin.com/fAGejcWu
https://pastebin.com/6PYp9kXd

And yes, I agree that only because a mod is in the list, does not mean it is the cause.
However, most often, changing *some thing* may help to get to the real cause.

**Comment by sri-arjuna** [comment]
4f6033256c2810619f81f28b1f4e0ab7899c0d4f

**Comment by sheson** [comment]
I am not sure what a post on the xLODGen thread about disabling auto saves to fix a long known vanilla bug with flickering water in Skyrim LE has to do with CTDs, scripts or DynDOLOD?

Correct me if I am wrong but this statement is made when DynDOLOD.esm is found:
"There is a chance that this might cause a CTD when changing locations." 
I have yet to see any kind of report or troubleshooting where the act of changing locations causes CTD in conjunction with DynDOLOD. There can be something in the new location that causes CTD but that would typically be invalid assets or record in plugins etc. causing issue regardless of auto saves / leaving a location. There can be a CTD when the game saves, like the buffer overflow of lz4 etc. These CTDs typically have easily readable crash logs.

"Specificly when passing a door of some sorts, can cause the game its AUTO-SAVE to be triggered, because the scripts were not done when its called and thus make the game stall."
before making this claim, the problem needs to be reported with crash logs etc, and troubleshooted. By all we know this claim does not make sense right now, especially in conjunction with DynDOLOD and its scripts.

First bug report you linked has a crash in FPSFixPlugin.dll which does not use scripts AFAIK. There is no DynDOLOD in the load order.

The second crash log points to a problem with water collision/updating placeable water. While there is DynDOLOD.esm in the load order, there is no hint that there is/was a save happening, no mentioning of the VM or any record or assets from DynDOLOD being involved.

If there is any kind of crash log that shows a crash where DynDOLOD, its scripts and (auto)save is involved I would address the issue one way or the other so that this crash does not happen anymore. IIRC so far all the CTD reports saving the game were about the lz4 buffer overflow, hence it is one of the actual credible CTD solutions explained in the DynDOLOD FAQ/ readme.

**Comment by sri-arjuna** [comment]
Can we cut this short/er please?
How shall i change the text for you to be happy?

All i know is, that users have confirmed that disabling auto-save helped them in such a situation.
And that action has been reported to me by another user.
All i did was implemting that advice.

I dont use DynDOLOD or xLODgen, and i have no interest in "digging deep" into each and every mod out there.
I do understand that DynDOLOD is hughe, and thus I ask again.

How shall i change the text? --> https://github.com/sri-arjuna/SSE-CLA/commit/4f6033256c2810619f81f28b1f4e0ab7899c0d4f
And/or can you please give me a hint as for what to scan for that "definitly" would be an issue with your mod? (if such a case would/should (ever) arise) - so we both can enjoy a relaxed weekend?

**Comment by sheson** [comment]
If you want to include a message for DynDOLOD, then it would be great if it could direct users to the [DynDOLOD FAQ](https://dyndolod.info/FAQ#ILS-or-CTD) and/or just direct them to the [official DynDOLOD support forum](https://stepmodifications.org/forum/forum/223-dyndolod-xlodgen/) for qualified troubleshooting help or to report the problem.
It helps if users would pay attention to the [error and warning messages](https://dyndolod.info/Messages#Warning-and-Error-Messages) in the DynDOLOD log. It may already contain possible reasons for problems including typical causes for CTD.

There is nothing special about the DynDOLOD plugins or scripts. It is references placing models. The scripts enable/disable them. In case DynDOLOD DLL NG is used, then they are enabled/disabled by it instead and scripts only help with settings/MCM.

Most CTDs are usually caused by models or textures, save buffer overrun. Sometimes users forget to make a clean save and old save data conflicts with new/different records in the plugins.
If there are reference/base records mentioned in DynDOLOD plugins it usually because they use/enable invalid assets, or sometimes unresolved form id because the user screwed up the process.

**Comment by sri-arjuna** [comment]
That is..
exactly what I had done in the hash-ref link, and what i was asking you, if that suits your expectations.
That (ref-link above) is now "live" in the 1.2 release a few days ago on nexus.

Well, i'll be including the links you provided now, 3 weeks later, in the next update.

Note to self: (just to see if the URL preserve)
* https://dyndolod.info/FAQ#ILS-or-CTD
* https://stepmodifications.org/forum/forum/223-dyndolod-xlodgen/
* https://dyndolod.info/Messages#Warning-and-Error-Messages
